-- AlterTable
ALTER TABLE "public"."notes" ADD COLUMN     "positionX" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "positionY" DOUBLE PRECISION NOT NULL DEFAULT 0,
ADD COLUMN     "zIndex" INTEGER NOT NULL DEFAULT 0;
